module Sentiments
//https://www.theatlantic.com/technology/archive/2016/07/the-200-happiest-words-in-literature/490916/

let sad_sentiment = ["Sorrow"; "Grief"; "Despair"; "Melancholy"; "Heartache"; "Misery"; "Anguish"; "Loneliness"; "Regret"; "Isolation"; "Disappointment"; "Forlorn"; "Dejected"; "Woeful"; "Dismay"; "Woe"; "Mournful"; "Lament"; "Abandoned"; "Desolation"; "Bleak"; "Crestfallen"; "Tragic"; "Depressed"; "Broken"]
let happy_sentiment = ["Laughter"; "happiness"; "love"; "happy"; "laughed"; "laugh"; "laughing"; "excellent"; "laughs"; "joy"; "successful"; "win"; "rainbow"; "smile"; "won"; "pleasure"; "smiled"; "rainbows"; "winning"; "celebration"; "enjoyed"; "healthy"; "music"; "celebrating"; "congratulations"; "weekend"; "celebrate"; "comedy"; "jokes"; "rich"; "victory"; "Christmas"; "free"; "friendship"; "fun"; "holidays"; "loved"; "loves"; "loving"; "beach"; "kissing"; "sunshine"; "delicious"; "friends"; "funny"; "outstanding"; "paradise"; "sweetest"; "vacation"; "butterflies"; "freedom"; "flower"; "great"; "sunlight"; "sweetheart"; "sweetness"; "award"; "chocolate"; "heaven"; "peace"; "splendid"; "success"; "enjoying"; "kissed"; "attraction"; "celebrated"; "hero"; "hugs"; "positive"; "sun"; "birthday"; "blessed"; "fantastic"; "winner"; "delight"; "beauty"; "butterfly"; "entertainment"; "funniest"; "honesty"; "sky"; "smiles"; "succeed"; "wonderful"; "glorious"; "kisses"; "promotion"; "family"; "gift"; "humor"; "romantic"; "cupcakes"; "festival"; "honour"; "relax"; "weekends"; "angel"; "bonus"; "brilliant"; "diamonds"; "holiday"; "lucky"; "mother"; "super"; "amazing"; "angels"; "enjoy"; "friend"; "friendly"; "mother's"; "profit"; "finest"; "champion"; "grandmother"; "kiss"; "kitten"; "miracle"; "mom"; "sweet"; "blessings"; "bright"; "cutest"; "entertaining"; "excited"; "excitement"; "joke"; "millionaire"; "prize"; "succeeded"; "successfully"; "winners"; "shines"; "awesome"; "genius"; "achievement"; "cake"; "cheers"; "exciting"; "goodness"; "hug"; "income"; "party"; "puppy"; "smiling"; "song"; "succeeding"; "tasty"; "victories"; "achieved"; "billion"; "cakes"; "easier"; "flowers"; "gifts"; "gold"; "merry"; "families"; "handsome"; "lovers"; "affection"; "candy"; "cute"; "diamond"; "earnings"; "interesting"; "peacefully"; "praise"; "relaxing"; "roses"; "Saturdays"; "faithful"; "heavens"; "cherish"; "comfort"; "congrats"; "cupcake"; "earn"; "extraordinary"; "glory"; "hilarious"; "moonlight"; "optimistic"; "peaceful"; "romance"; "feast"; "attractive"; "glad"; "grandma"; "internet"; "pleasant"; "profits"; "smart"]

let funny_sentiment = ["Hilarious" ;"Witty" ;"Amusing" ;"Comical" ;"Jovial" ;"Whimsical" ;"Zany";"Lighthearted" ;"Jocular" ;"Gleeful" ;"Eccentric" ;"Quirky" ;"Ridiculous" ;"Absurd" ;"Farcical" ;"Playful" ;"Hysterical" ;"Funny"]

let angry_sentiment = ["Furious";"Wrath";"Irritated";"Agitated";"Resentful";"Annoyed";"Incensed";"Livid";"Enraged";"Infuriated";"Exasperated";"Indignant";"Cross";"Vexed";"Irate";"Outraged";"Mad";"Hostile";"Bitter";"Fuming"]



